In [ ]:
from __future__ import print_function
import torch
import numpy as np

In [ ]:
########################################################################
# Doc : https://pytorch.org/docs/stable/torch.html#tensors
########################################################################


In [ ]:
### Declarations

# Declarer (sans initialiser) un Tensor pyTorch (3x2)
x = torch.empty(3, 2)
print(x)



tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [ ]:
# Declarer et initialiser un Tensor pyTorch (3x2)
x = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(x)


tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
# Declarer un Tensor (4,2) dont tous les elements sont initialise a zero
x = torch.zeros(4, 2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [ ]:
# Declarer un Tensor (5x3) aleatoirement initialise
x = torch.rand(5, 3)
print(x)


tensor([[0.8915, 0.2752, 0.5156],
        [0.6372, 0.5401, 0.7315],
        [0.0916, 0.9428, 0.3985],
        [0.3087, 0.2071, 0.8593],
        [0.8514, 0.7907, 0.5439]])


In [ ]:
# Declarer un Tensor (3x3) dont les valeurs sont initialisees entre 0 et 1 suivant une loi normale
x = torch.randn(3, 3)
print(x)


tensor([[ 0.3870, -0.2898, -0.6559],
        [ 0.7906, -1.5173,  0.3817],
        [ 0.4731,  0.3201,  0.1200]])


In [ ]:
# Declarer un batch de 10 Tensor (3x3) initilise aleatoirement
batch = torch.rand(10, 3, 3)
print(batch)


tensor([[[0.5484, 0.5915, 0.4779],
         [0.5106, 0.7934, 0.3559],
         [0.1714, 0.3974, 0.4777]],

        [[0.8495, 0.1844, 0.0995],
         [0.0825, 0.8176, 0.7526],
         [0.7576, 0.9700, 0.7491]],

        [[0.0827, 0.5560, 0.2308],
         [0.2841, 0.4534, 0.1167],
         [0.3444, 0.2783, 0.1118]],

        [[0.7455, 0.0882, 0.8045],
         [0.1382, 0.4830, 0.4138],
         [0.9828, 0.2633, 0.7030]],

        [[0.5567, 0.0253, 0.6579],
         [0.4173, 0.2388, 0.5036],
         [0.5983, 0.4136, 0.3074]],

        [[0.6942, 0.8116, 0.4886],
         [0.5382, 0.9393, 0.9769],
         [0.1182, 0.8489, 0.5967]],

        [[0.2937, 0.9971, 0.4583],
         [0.8918, 0.9199, 0.1571],
         [0.9382, 0.1366, 0.5454]],

        [[0.4733, 0.4825, 0.1506],
         [0.9472, 0.7943, 0.7085],
         [0.6310, 0.5196, 0.5753]],

        [[0.4453, 0.5044, 0.9712],
         [0.6056, 0.1385, 0.5285],
         [0.3833, 0.9360, 0.9289]],

        [[0.8938, 0.9394, 0.7637],
  

In [ ]:
### Operations

# Additionner un Tensor (2x2) avec un scalaire
z = torch.rand(2, 2) + 5
print(z)

tensor([[5.7530, 5.6869],
        [5.7454, 5.7372]])


In [ ]:
### Operations

# Additionner un Tensor (2x2) avec un scalaire
z = torch.rand(2, 2) + 5
print(z)

tensor([[5.3765, 5.2186],
        [5.9359, 5.4461]])


In [ ]:
# Mutliplier un Tensor (5x2) par un Tensor (2x3)
a = torch.rand(5, 2)
b = torch.rand(2, 3)
c = torch.mm(a, b)
print(a)
print(b)
print(c)


tensor([[0.7878, 0.0965],
        [0.0189, 0.2410],
        [0.9453, 0.8501],
        [0.8335, 0.6743],
        [0.8449, 0.8890]])
tensor([[0.0745, 0.5278, 0.4714],
        [0.8569, 0.7264, 0.1699]])
tensor([[0.1413, 0.4859, 0.3878],
        [0.2079, 0.1850, 0.0499],
        [0.7989, 1.1164, 0.5900],
        [0.6399, 0.9297, 0.5075],
        [0.8247, 1.0917, 0.5494]])


In [ ]:
# Mutliplier 2 batch de 3 Tensor (2x2)
batch1 = torch.rand(3, 2, 2)
batch2 = torch.rand(3, 2, 2)
r = torch.bmm(batch1, batch2)
print(batch1)
print(batch2)
print(r)
print(batch1[0])
print(batch2[0])
print(r[0])

tensor([[[0.3178, 0.4702],
         [0.8654, 0.4879]],

        [[0.6124, 0.2745],
         [0.3720, 0.5832]],

        [[0.3461, 0.2441],
         [0.2157, 0.9626]]])
tensor([[[0.6718, 0.7200],
         [0.3374, 0.9046]],

        [[0.7868, 0.9680],
         [0.2657, 0.9901]],

        [[0.6535, 0.5040],
         [0.9897, 0.6182]]])
tensor([[[0.3722, 0.6542],
         [0.7460, 1.0644]],

        [[0.5547, 0.8645],
         [0.4476, 0.9375]],

        [[0.4678, 0.3253],
         [1.0937, 0.7038]]])
tensor([[0.3178, 0.4702],
        [0.8654, 0.4879]])
tensor([[0.6718, 0.7200],
        [0.3374, 0.9046]])
tensor([[0.3722, 0.6542],
        [0.7460, 1.0644]])


In [ ]:
### Slincing Indexing Joining Mutating

# Declarer un Tensor de 9 elements puis le formater en Tensor (3x3)
v = torch.arange(9)
v = v.view(3, 3)
print(v)

# Concatener deux Tensor (2x2)
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.cat((a, b), 0)
print(c)

# Declarer un Tensor (10,5) et afficher sa premiere colonne
a = torch.rand(10, 5)
print(a)
print(a[:, 0])


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0.0789, 0.5055],
        [0.8777, 0.3280],
        [0.6235, 0.2930],
        [0.5103, 0.4618]])
tensor([[0.9502, 0.7870, 0.3756, 0.4613, 0.2308],
        [0.4253, 0.2851, 0.6782, 0.7764, 0.9367],
        [0.9744, 0.6587, 0.0266, 0.3757, 0.9314],
        [0.7025, 0.3028, 0.9075, 0.7694, 0.8673],
        [0.2923, 0.7330, 0.2421, 0.2030, 0.4917],
        [0.4944, 0.5781, 0.0091, 0.4969, 0.0991],
        [0.4872, 0.1119, 0.9303, 0.8362, 0.0790],
        [0.8873, 0.5622, 0.1455, 0.9907, 0.2107],
        [0.0460, 0.6909, 0.8698, 0.4121, 0.4493],
        [0.9953, 0.7696, 0.8622, 0.6011, 0.6331]])
tensor([0.9502, 0.4253, 0.9744, 0.7025, 0.2923, 0.4944, 0.4872, 0.8873, 0.0460,
        0.9953])
